name: Pathfinding
version: ${project.version}
main: sk.infivi.pathfinding.Pathfinding
api-version: 1.17
commands:

  pathfinding:
    description: Control the plugin easily, in chat.
    usage: /<command>
    aliases:
      - menu
      - options

  startsearch:
    description: Start the search.
    usage: /<command>
    aliases:
      - start
      - run

  algorithm:
    description: Set the pathfinding algorithm.
    usage: /<command> <algorithm>
    aliases:
      - al

  selectblockplane:
    description: Select the block plane to draw into.
    usage: /<command> <yLevel> <x1> <z1> <x2> <z2>

  mode:
    description: Set drawing mode.
    usage: /<command> <mode>

  speed:
    description: Set the speed of drawing (1 - 10).
    usage: /<command> <valuespeed>

  getitems:
    description: Get items for pathfinding visualisation.
    usage: /<command>
    aliases:
      - gi

  clearplane:
    description: Clear the plane.
    usage: /<command>
    aliases:
      - c

  silent:
    description: Toggle silent mode.
    usage: /<command>

  refresh:
    description: Toggle refresh mode.
    usage: /<command>

  random:
    description: Toggle random mode.
    usage: /<command>